import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/header";
import Pagetransation from "@/components/Header/pagetransation";
import Staticeffect from "@/components/Header/staticeffect";
import { Toaster } from 'react-hot-toast';
const JetbrainsMono = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono'
});

export const metadata = {
  title: "Srajit Mishra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JetbrainsMono.variable}>
        <Header />
        <Toaster />
         <Staticeffect/> 
       <Pagetransation > {children}</Pagetransation>
      </body>
    </html>
  );
}
